### ISSUE TITLE
How to use CoreAs?

### ISSUE THREAD

**Issue by m0ose** [backspaces/agentscript#1]
I tried to use it in a similar way to asx ...
``` javascript
import {Model, util} from '../../dist/AS.module.js'

util.toWindow({ Model, util })

class SnorlaxInvaders extends Model {
  setup () {
  }

  step () {  
  }
}
const options = Model.defaultWorld(1, 80)
const model = new SnorlaxInvaders(document.body, options)
model.setup()
model.start()

const {world, patches, turtles} = model
util.toWindow({ world, patches, turtles, model })
```

and I got an error

```
running: ./src/airAttack.js dir: src name: airAttack.js
AS.module.js:130 toWindow: Model, util
AS.module.js:2518 Uncaught TypeError: Cannot read property 'reset' of undefined
    at AirAttackers.reset (AS.module.js:2518)
    at new Model (AS.module.js:2467)
    at new AirAttackers (airAttack.js:8)
    at airAttack.js:20
reset @ AS.module.js:2518
Model @ AS.module.js:2467
AirAttackers @ airAttack.js:8
(anonymous) @ airAttack.js:20
```

**Comment by backspaces** [comment]
Two changes:
1 - Remove the div from the ctor should do the trick. The ctor for core (I.e. the Model, not the View) doesn't need the div or the rendererOptions, just the world.
2 - The world options no longer uses the patchSize. It's always one. 

In other words, when removing all the View artifacts, both these occurred. I'm sorry I didn't get this out there. I'll try to get a model working to check all the problems that may crop up.

**Comment by backspaces** [comment]
Sigh, also forgot to mention: there is no start(). Stephen felt the animator was not necessary.

We may decide to have the animator, though. The point he had was that models will likely have an "app" run the model using other ways of advancing the model's "time". And maybe even recording history for "scrubbing" the model.

**Comment by backspaces** [comment]
I'm closing this for now but we need to solve the Model/View architecture, and figure out how to integrate asx/AgentScript into the same repo? That way we could have one set of issues. I think that might be a good thing.
