### ISSUE TITLE
Dataset.normalize broken: lerp is not defined

### ISSUE THREAD

**Issue by m0ose** [backspaces/agentscript#16]
It looks like Dataset normalize is not working because lerp is not defined.

https://github.com/backspaces/agentscript/blob/d95a30337bbbfae5f44b2b3de76bfa1e52751bbf/src/DataSet.js#L425

**Comment by backspaces** [comment]
Nice catch: it lives in util, i.e. util.lerp(). I'll fix it this afternoon.

**Comment by backspaces** [comment]
Should be fixed now.  If you can try it easily, let me know if it works for you.

**Comment by backspaces** [comment]
I'll close this, can reopen if problems
