### ISSUE TITLE
Is the mouse callback order evt,mouse or mouse,evt?

### ISSUE THREAD

**Issue by stigmergic** [backspaces/agentscript#19]
Looks like there are two orders here:
https://github.com/backspaces/agentscript/blob/4a32a2f5ded4c75e21f3b11113e5095da83435f5/src/Mouse.js#L4
vs
https://github.com/backspaces/agentscript/blob/4a32a2f5ded4c75e21f3b11113e5095da83435f5/src/Mouse.js#L62

**Comment by backspaces** [comment]
Oops, should be the second.
See the one-pager https://backspaces.github.io/onepagers/mouse.html
.. I'll build one like it in views2/

**Comment by backspaces** [comment]
See this: https://agentscript.org/views2/mouse.html
