### ISSUE TITLE
Consider merging both options objects for `TwoDraw` into one

### ISSUE THREAD

**Issue by bennlich** [backspaces/agentscript#21]
I've been fooled twice! Once a few months ago, and then again the other day. In the examples I see:
```
const view = new TwoDraw(model, {
    div: 'modelDiv',
    patchSize: 40
})
```
and then [in the source for `TwoDraw`](https://github.com/backspaces/agentscript/blob/master/src/TwoDraw.js#L7-L29) I see that `patchesColor` is a config option, so I immediately try:
```
const view = new TwoDraw(model, {
    div: 'modelDiv',
    patchSize: 40,
    patchesColor: 'white'
})
```
But it's really supposed to go in the **second** options object, like so:
```
const view = new TwoDraw(model, {
    div: 'modelDiv',
    patchSize: 40
}, {
  patchesColor: 'white'
})
```
I think this is really confusing, especially because there's an option called `turtlesSize` which can't go next to `patchSize` :thinking: 

Can we just have one options object?

**Comment by backspaces** [comment]
I want the draw object to remain separate:
- It is a single set of draw options that are similar for both two and three draw.
- Mixing them in with the view options would complicate the draw() function .. it would have to separate out the non-draw div, etc.
- Three has potentially very complex view options which would be even more complicated.

So the "architecture" for both TwoDraw and ThreeDraw is World, ViewOptions, DrawOptions. TwoView & ThreeView have only the first two. And even tho we do tend to use the Draw versions, it started as an experiment a while back and there are cases where the View versions are simpler, but the declarative nature of the Draw versions are more expressive.

**Comment by backspaces** [comment]
HOWEVER! :)

I think the problem could be reduced by getting rid of patchSize. It's only used in 2D, not 3D. And I think it would be preferred to use a Width parameter instead.

It is inherited from NL and in the JS world, providing a width parameter for the 2D canvas would clarify when you can use floats vs ints: the World object has to be integer values (I'll warn, as you suggest, if non-integer) while the drawing area can be any size, resulting in fractional patch sizes being OK

**Comment by stigmergic** [comment]
What I am understanding here is that the view options are for configuring the view as a widget (general viewer) while the drawOptions are used for specifying how a given model should be drawn?  Guess I am looking for the rules around when/what properties would go in each category.

**Comment by backspaces** [comment]
Would it be preferable to put the draw object in the options option, so one set of options?

const view = new TwoDraw(model, {
    div: 'modelDiv',
    patchSize: 40,
    drawOptions: {
        patchesColor: 'white'
    }
})

It would require TwoDraw to remove the drawOptions before calling it's super class, but that's not crazy. 

It does, however, bring up the question of what to do if drawOptions isn't present. It could be a misspelling of drawOptions, or simply as it is now, asking for the default options.

**Comment by bennlich** [comment]
> Would it be preferable to put the draw object in the options option, so one set of options?

Yes! If they must be separate, this would be an improvement.

> What I am understanding here is that the view options are for configuring the view as a widget (general viewer) while the drawOptions are used for specifying how a given model should be drawn? Guess I am looking for the rules around when/what properties would go in each category.

@backspaces is @stigmergic 's understanding correct?

**Comment by backspaces** [comment]
Here's the deal:
TwoView is a basic set of methods for patches, turtles, links drawing.
TwoDraw is a subclass of TwoView with a declarative interface: the drawOptions.

TwoDraw is meant to simplify the most common cases but there are times when TwoView is better. IIRC tho, all our demos are now using TwoDraw (or ThreeDraw)

**Comment by backspaces** [comment]
OK, I'm experimenting with this. For now, both will be legal:
- Put the drawOptions in the viewOptions, the second argument.
  - (gotta use the right name.
  - It will be deleted from the viewOptions
- Put the drawOptions as the third argument

This will allow us to keep our current views the same without change. We can upgrade our existing views over time, but document the first option as the default.

I'll let you know if it turns into a problem after using it a bit.

**Comment by backspaces** [comment]
Should be in latest commit
