### ISSUE TITLE
Passing a TypedColor into patchesColor doesn't seem to work

### ISSUE THREAD

**Issue by bennlich** [backspaces/agentscript#22]
E.g. in flock.html, try replacing https://github.com/backspaces/agentscript/blob/master/views2/flock.html#L17-L20 with the following:

```
                import Color from '../src/Color.js'
                const view = new TwoDraw(model, {
                    div: 'modelDiv',
                    patchSize: 15,
                }, {
                  patchesColor: Color.typedColor('white')
                }) // defalt drawOptions!
```
It seems to work if you change `view.clear(patchesColor)` to `view.clear(patchesColor.css)` here: https://github.com/backspaces/agentscript/blob/master/src/TwoDraw.js#L108

**Comment by backspaces** [comment]
Good catch!

The goal is to let us use any sort of color in the modeler's API and converting to the required version where needed. The typedcolor should be OK anywhere so this is a bug, will track down and fix.

**Comment by backspaces** [comment]
Fixed: src/utils.js clearCtx(ctx, cssColor): cssColor = cssColor.css || cssColor
