### ISSUE TITLE
patchesColor doesn't do what I thought with a function that returns a color string

### ISSUE THREAD

**Issue by bennlich** [backspaces/agentscript#29]
In drawOptions, this works:
```
{
    patchesColor: p => Color.typedColor('red')
}
```

But this does not:
```
{
    patchesColor: p => 'red'
}
```
Though it did lead to this beautiful image:

![Screenshot from 2021-02-19 15-41-06](https://user-images.githubusercontent.com/704368/108573370-38b04080-72c9-11eb-89e6-3ee39c954121.png)

**Comment by backspaces** [comment]
Good catch! Patches use pixels, believe it or not! I try to convert everything to typedColors but this is a leak.

**Comment by backspaces** [comment]
OK, a quick note: The way to color all the patches the same color is:
```
    {
        patchesColor: 'red' 
    }
```
i.e. there is no dependency on "p".

Basically it is treated as "clear the canvas with this color"

The form (with the great colors!) should work, let me poke around.

**Comment by backspaces** [comment]
OK I think I found the problem. Damn there are a lot of color formats in JS!

It is less efficient to set each patch's color, that's thousands of operations, one per patch.
God do I need to document this stuff.

**Comment by backspaces** [comment]
OK, committed the fix.
