### ISSUE TITLE
Support degrees in turtle.rotate() and elsewhere

### ISSUE THREAD

**Issue by bennlich** [backspaces/agentscript#31]
At least for our tutorials and IDE, I think it would be nice to support degrees by default when dealing with angles.

**Comment by backspaces** [comment]
Yes, this makes sense especially as we try to teach AS "incrementally" to new modelers. 

JS programmers may want to stick with JS's radians like used in Math and Canvas and also in JS libraries like Three.js.

I'll take a crack at this in Turtle.js (2D) initially and see if we like it. It will allow both JS radians and degrees.

**Comment by backspaces** [comment]
I've started on this with Model.js supporting "setGeometry(name)". I've got Turtle.js translated but there will be a lot of work to complete it. Maybe all but Turtle3D in a week or two.

**Comment by backspaces** [comment]
OK, the model.setGeometry() transform stunt apparently works. There are currently three choices:
"radians": Basic JS euclidean radians. I.e. what it has been.
"degrees": The above with degrees rather than radians
"heading": The NL clock model: y axis is "0", angles are ClockWise (negative of JS angles)

The default is currently set to "radians" because it would break all the demos/models otherwise. So you'll want to set it to degrees or heading.

**Comment by backspaces** [comment]
I completed the first pass of model.geometry for both Turtle.js & Turtle3D.
The views3d/nav.html model should now be fully functional, letting you see just how NL clock geometry works.
I'm closing this for now, but likely several bugs .. just make issues.
Next step is to convert all models to use this.

**Comment by backspaces** [comment]
I completed the first pass of model.geometry for both Turtle.js & Turtle3D.
The views3d/nav.html model should now be fully functional, letting you see just how NL clock geometry works.
I'm closing this for now, but likely several bugs .. just make issues.
Next step is to convert all models to use this.

**Comment by backspaces** [comment]
I completed the first pass of model.geometry for both Turtle.js & Turtle3D.
The views3d/nav.html model should now be fully functional, letting you see just how NL clock geometry works.
I'm closing this for now, but likely several bugs .. just make issues.
Next step is to convert all models to use this.
