### ISSUE TITLE
code mirror in IDE may need a refresh()

### ISSUE THREAD

**Issue by stephenguerin** [backspaces/agentscript#46]
script text and line numbers aren't fully rendering on Chrome. Tested on two windows 10, Android chrome and chromebook:

![image](https://user-images.githubusercontent.com/1078567/118402581-be712d00-b627-11eb-8fd8-79163884408a.png)

**Comment by backspaces** [comment]
@stephenguerin Could you post either the html file or pebble so we could recreate the issue?

**Comment by stephenguerin** [comment]
I am just using the example pebbles. I see the same behavior on Edge. 

As I play with the bug, on any of the pages with an issue, if I reduce patchSize or Width in the view and toggle back into Model tab it renders fine. And if I increase patchSize or Width over some threshold, I can bring back the rendering bug.

Do you see the same issue?

 I suspect it has to do with the code mirror text area resize event and maybe needing a code-mirrir.refresh()

**Comment by backspaces** [comment]
I'm closing this. Lets move it to the editor repo if it is still important
