### ISSUE TITLE
Understanding diffuse

### ISSUE THREAD

**Issue by bennlich** [backspaces/agentscript#47]
@backspaces I'm looking w/ my dad at https://github.com/backspaces/agentscript/blob/master/src/Patches.js#L301 :

```
const dv = p[v] * rate            
const dvn = dv / n            
const neighbors = n === 8 ? p.neighbors : p.neighbors4            
const nn = neighbors.length
p._diffuseNext += p[v] - dv + (n - nn) * dvn
```

I'm having trouble understanding the last term on the last line. Isn't `(n - nn)` always 0?

**Comment by stephenguerin** [comment]
corners have nn = 3 neighbors and edges have nn= 5. they will be different
than from n when n=4 or 8. I watched that with the debugger :-) I set a
conditional breakpoint to pause whenever n != nn and saw it pausing on the
patches with 3's and 5s.

[image: image.png]

**Comment by stephenguerin** [comment]
corner patches have neighbors (nn) = 3 neighbors and edge patches have nn = 5. they will be different
than from n when n=4 or 8. To explore this I set a
*conditional* breakpoint to pause whenever n != nn and saw it pausing on the
patches with 3's and 5s. Note in the image below the debugger is currently paused on patch id 4 with 5 neighbors

![image](https://user-images.githubusercontent.com/1078567/119194682-b0187c00-ba40-11eb-8700-43e8dff4ff04.png)

**Comment by stephenguerin** [comment]
To edit a breakpoint to be conditional, right click on it and put in your expression. 

![image](https://user-images.githubusercontent.com/1078567/119195156-68462480-ba41-11eb-8b29-c7be7640de0b.png)


You can also have the option to make a "logpoint" here which is convenient for console logging especially when you can't modify the source:

https://www.thedevelobear.com/post/logpoints/

**Comment by stephenguerin** [comment]
I suspect Benny's dad want's to know if the diffuse process conserves the quantity being diffused. I am a little unsure looking at the code even though I once answered him with a confident yes :-) Reading through Owen's code (very cool btw), I think it is true.

**Comment by bennlich** [comment]
Ahhhhh, I see. Nice breakdown. Thanks @stephenguerin

**Comment by plichtner** [comment]
I diffusion unstable if rate > 1? See attached figure with rate = 1.5.

<img width="1221" alt="Screen Shot 2021-05-21 at 10 25 40 AM" src="https://user-images.githubusercontent.com/6454920/119198444-9843f680-ba46-11eb-81cd-f7e0888b7fd2.png">
