### ISSUE TITLE
Example of addPath

### ISSUE THREAD

**Issue by yuichiroaoki** [backspaces/agentscript#56]
I would appreciate if you could show some examples of adding custom turtle shapes with addPath function in src/Shape.js.

I was trying to add custom shapes and found the comments below, but I'm not sure how to do it.
https://github.com/backspaces/agentscript/blob/bd718359f0751c1eb593c437cd23702273a9a248/src/Shapes.js#L138

Also is it possible to add new shapes from the editor showing examples?

**Comment by backspaces** [comment]
Hi! Sorry to be late responding. I'll get to it shortly.

**Comment by yuichiroaoki** [comment]
> Hi! Sorry to be late responding. I'll get to it shortly.

Thank you !!

**Comment by backspaces** [comment]
There is a sample model in the views2/ folder that shows adding image "shapes". Using images is often used when the shape is too complex for simple canvas drawing used by the src/Shapes.js module.

> https://code.agentscript.org/views2/shapes.html

This is way to complex for a simple shapes tutorial but I just wanted to point to an existing sample. It runs all the built-in shapes with random colors. The two newly added shapes are the images for twitter and redfish group (us!)

I'll try to pair this down into something more usable as a tutorial, but at least you can see one sort of addition there.

Note: I'm on my way out of the country for a 7 week vacation in Italy. And at the last minute they changed all of the EU covid travel protocols so I'm running like crazy to adjust our plans. I do hope to at least add a non-image shape to views2/shapes.html but hard to predict.

**Comment by yuichiroaoki** [comment]
Thank you. Now I understand how this all works. I'm going to add new shapes with images instead of using addPath function. 
Hope you're having a wonderful vacation!

**Comment by backspaces** [comment]
Thanks! Note that the "image" can also be a canvas that you've drawn on for a custom, in model, "shape".
