### ISSUE TITLE
agentscript.esm.js does not exist anymore

### ISSUE THREAD

**Issue by m0ose** [backspaces/agentscript#63]
https://github.com/backspaces/agentscript/blob/844d7f4c67e3efc684376e7e6c7c78c7181b6495/package.json#L8

This line of the package.json file is outdated. It is causing the skypack version to not work.

**Comment by backspaces** [comment]
Fixed:
    "module": "dist/agentscript.js",
I'll publish this as well so cdn's should work

**Comment by backspaces** [comment]
yarn publish && git push --follow-tags

>   info Current version: 0.10.16
>   question New version: 0.10.17
>

**Comment by backspaces** [comment]
Let me know if this works.
