### ISSUE TITLE
request elevation for bbox without leaflet view

### ISSUE THREAD

**Issue by m0ose** [backspaces/agentscript#66]
The function **getBBoxDataSet**  requires a Leaflet map and an elevation layer to be added to that map. It would be nice to be able to load elevation for a bbox without the leaflet map at all. 

https://github.com/backspaces/agentscript/blob/3e2a6e7ca4edc375f1deb823527650879bc1d704/gis/LeafletDataSet.js#L83-L84

**Comment by backspaces** [comment]
Yes indeed! Could you submit an Issue? Helps me prioritize. Thanks!

**Comment by backspaces** [comment]
Oops, didn't see that it WAS an issue. Sigh! Thanks

**Comment by backspaces** [comment]
OK: is what you'd like is for 

> async getBBoxDataSet(bbox) 

to use the bbox to discover the required tilles, fetch them, and when all are fetched, proceed to stitch the associated datasets together, get the crop/clip params, and return the single cropped set?

And if it's called several times, manage the set of tiles .. or maybe just rely on the browser cache to do it for me, I'll always do the complete set of fetches and hope the cache works well.

**Comment by m0ose** [comment]
Yeah. That's what I was thinking. Do you think it would be useful?

**Comment by m0ose** [comment]
Would we need to pass a zoom? or width and height of the final dataset and guess the zoom?

**Comment by backspaces** [comment]
I think it would be useful, sure. We'd need to pass in a lot of info including the zoom and what the tile rgb dataset would be (TileData.js: mapzen, mapbox, redfish etc).

**Comment by backspaces** [comment]
Completed gis/BBoxDataSet.js in, converted gis/droplets.html and other users of LeafletDataSet to use it. Removed LeafletDataSet from repo.
