### ISSUE TITLE
step is not defined

### ISSUE THREAD

**Issue by m0ose** [backspaces/agentscript#73]
https://github.com/backspaces/agentscript/blob/d97ac75f4e2c823a5bab2ecb4e06ee95002322e4/src/domUtils.js#L217

**Comment by m0ose** [comment]
I think step needs to be imported from jsUtils too.
https://github.com/backspaces/agentscript/blob/d97ac75f4e2c823a5bab2ecb4e06ee95002322e4/src/domUtils.js#L6

**Comment by backspaces** [comment]
Yup, nice catch. I may change from having jsUtils & domUtils to just jsUtils and utils. It's kinda awkward the way it is. And I doubt anyone really needs domUtils by itself? I made the split initially to make sure Deno did not have any dom code lurking to explode! :)

**Comment by backspaces** [comment]
Fixed.  .. I hope!

**Comment by m0ose** [comment]
I hope too 🤞
