### ISSUE TITLE
docs 404

### ISSUE THREAD

**Issue by ruckc** [backspaces/agentscript#79]
I found this during a hackathon.  I really like the simplicity... but the docs don't work, it 404's on github pages.

**Comment by backspaces** [comment]
Thanks! I'll look at the docs build script, maybe it's broken.

**Comment by backspaces** [comment]
This is fixed, see https://code.agentscript.org/docs/agentscript/0.10.19/
The odd path is being looked into: https://github.com/ankitskvmdam/clean-jsdoc-theme/issues/240
But the user doesn't use that, they click on the docs link in the README greeting link.

**Comment by backspaces** [comment]
I've added an index.html to docs/ which forwards to docs/agentscript/0.10.19/ so that going to https://code.agentscript.org/docs works as before. 

So we have work-arounds until we hear back from clean-jsdoc-theme.

I'll close this for now but we can re-open if problems pop up

**Comment by backspaces** [comment]
Docs now fixed, was based on package.json use which caused clean-jsdoc-theme to use the version etc. A miss-understanding and fixed.
