### ISSUE TITLE
Should mixin include set/get and non enumerables?

### ISSUE THREAD

**Issue by backspaces** [backspaces/agentscript#81]
As part of the color integration, I stumbled across the issue of mixing in *all* of an object into another.  This includes set/ge properties built with Object.defineProperty, see attached set of new clone/mixins in Util.  Should we make this general, for our "class" mixin function too?

    # Mix the attributes from one object into another
    mixinObject: (destObj, srcObject) ->
      # Get *all* own props, not just enumerable.
      keys = Object.getOwnPropertyNames(srcObject)
      for key in keys
        prop = Object.getOwnPropertyDescriptor(srcObject, key)
        Object.defineProperty(destObj, key, prop)
      destObj
    # Return a copy of an object, with the prototype also set in the copy
    # when the object has a prototype other than Object.prototype
    cloneObject: (obj) ->
      newObj = Object.create({}, Object.getPrototypeOf(obj))
      @mixinObject newObj, obj
    # Clone a class (a constructor function) including
    # a copied prototype.  This is used when we have multiple
    # models in a page when the prototype has global variables.
    cloneClass: (oldClass, newName) ->
      ctorStr = oldClass.toString().replace(/^/, "var ctor = ")
      if newName
        ctorStr = ctorStr.replace(/function.*(?=\()/, "function #{newName}")
      eval(ctorStr)
      ctor.prototype = @cloneObject(oldClass.prototype)
      ctor
    # Mix the attributes from one class into another;
    # an alternative to prototypal inheritance. Similar to extend, but
    # mixin() knows to copy prototype functions into the prototype
    mixin: (destObj, srcObject) ->
      destObj[key] = srcObject[key] for own key of srcObject
      destObj.__proto__[key] = srcObject.__proto__[key] for own key of srcObject.__proto__

**Comment by bennlich** [comment]
mixinObject *does not* mix in prototype attributes, right? Is that desired, or should we merge `mixinObject` and `mixin` into one function?

**Comment by backspaces** [comment]
I wondered about that too, so I checked for that in the console and AFAIK
it did not.  It does copy "prototype.constructor" in the case of classes
which we were doing anyway.

Mainly I wondered if you thought mixins should
1 - Include set/get properties
2 - Include all properties, not just enumerable ones.  This comes up with
set/get when built with Object.definePropery .. it has an enumerable flag.

**Comment by bennlich** [comment]
> Mainly I wondered if you thought mixins should
> 1 - Include set/get properties

yes

> 2 - Include all properties, not just enumerable ones.

I'm still a little fuzzy on what properties are enumerable and what are not.

**Comment by backspaces** [comment]
>
>
> Mainly I wondered if you thought mixins should
> 1 - Include set/get properties
>
> yes
>
> 2 - Include all properties, not just enumerable ones.
>
> I'm still a little fuzzy on what properties are enumerable and what are
> not.
>
​Well, mainly stuff in the protochain that want's to be invisible. Since
we're generally not groveling over these, I suspect we're OK.  To play with
these differences, use Object.keys to grab the enumerable keys, and
​Object.getOwnPropertyNames for everything (except, I hope, the proto
itself)

5   Object.keys(obj)
      Returns an array containing the names of all of the given
      obj own enumerable properties
5   Object.getOwnPropertyNames(obj)
      obj: The object whose enumerable and non-enumerable
        own properties are to be returned.
(The "5" is when it became standerd, es5)

**Comment by backspaces** [comment]
I think our current solution for cloning has resolved this: definedProperties are copied.  Indeed, all properties are, thanks to Object.getOwnPropertyNames, Object.getOwnPropertyDescriptor, Object.defineProperty and the rest of es5/6 property methods.
