### ISSUE TITLE
Turtles leave trails when using transparent patches

### ISSUE THREAD

**Issue by songololo** [backspaces/agentscript#82]
I'm using a MapDraw and so have set the patches to transparent except where pheromones exist, in which case a non zero opacity is set.

Due to using the transparent patches the turtles leave a non-disappearing trail: is there a way to flush or evaporate old turtle positions?

Thanks!

**Comment by songololo** [comment]
For now I'm trying to modify the `TwoDraw` function to add a `clear()` when the patches colour is a function per:
```js
// view.clear()

if (patchesColor === 'random' || initPatches) {
    view.clear() // patch transparent pixels do not clear the canvas!
    view.drawPatches() // redraw cached patches colors onto our view canvas
} else if (typeof patchesColor === 'function') {
    view.clear(); // ADDED
    view.drawPatches(model.patches, p => patchesColor(p))
} else if (util.isImageable(patchesColor)) {
    view.drawPatchesImage(patchesColor)
} else {
    view.clear(patchesColor)
}
```
This seems to clear the canvas though I'm not sure if this would be the best option.

**Comment by songololo** [comment]
Realising that the easier way to accomplish a clear is to add it to the animator function
```js
view.clear()
model.step()
view.draw()
```

**Comment by backspaces** [comment]
Hi Gareth, thanks for digging in!

Many of the GIS demos use transparency or opacity. Going to https://code.agentscript.org/ and then scroll down to leaflet or mapLibre will give easy access to several such examples. You can also just go to 
https://code.agentscript.org/leaflet/ & https://code.agentscript.org/maplibre/

These do not seem to have the problem but then they don't have individual patches with transparency or opacities. Sigh!

And judging from the MapDraw/TwoDraw code, transparency of individual patches was a problem:

```
    view.clear() // patch transparent pixels do not clear the canvas!
```

I really don't understand why we can't always clear. Your idea of adding clear for functions is pretty reasonable too.

Do you have a fairly simple example that I could start with?

**Comment by songololo** [comment]
@backspaces thanks for the response!

Adding `view.clear()` to the animation function seems to achieve the desired behaviour, so this is not really an issue, just needed to understand how to flush the draw state between steps:
```js
const anim = new Animator(
    () => {
      view.clear()
      model.step()
      view.draw()
    },
    1000,
    30,
  )
  anim.start()
```
I suppose this raises the question on whether It might be worth running clear by default via `view.draw()`, or whether this is an unnecessary performance hit for non transparent situations...?

**Comment by backspaces** [comment]
I think this would work:
```
if (util.isImageable(patchesColor)) {
    view.drawPatchesImage(patchesColor)
} else {
    view.clear()
    if (patchesColor === 'random' || initPatches) {
        view.drawPatches() // redraw cached patches colors onto our view canvas
    } else if (typeof patchesColor === 'function') {
        view.drawPatches(model.patches, p => patchesColor(p))
    }
}
```
I'll run it thru all my tests Monday and see there are problems.

**Comment by backspaces** [comment]
Using a package.json script to run all models in a folder, had to modify above. It seems to work now. Its been committed. Let me know if it works for you. I'll keep this open for a bit.

**Comment by songololo** [comment]
@backspaces works a charm! Thanks
