### ISSUE TITLE
mouse move doesn't work on with tiledata model

### ISSUE THREAD

**Issue by m0ose** [backspaces/agentscript#84]
I modified the tiledroplets demo to drop rain under the mouse and realized that it was returning the wrong patch under the mouse
```
 this.patches.on ('mousemove', function(mouseEvent) {
                    console.log('.')
                    agent = mouseEvent.target
                    agent.sprout(1)
                    console.log( agent.x, agent.y)
                    console.log( mouseEvent.originalEvent.offsetX, mouseEvent.originalEvent.offsetY)
                    console.log( mouseEvent.originalEvent)
                }.bind(this))

```
I think the problem comes from https://github.com/backspaces/agentscript/blob/master/lib/mouse.js#L79-L80 using offsetX and offsetY. It seems to be returning a position relative to the tile image instead of the whole viewport.  Maybe pageX/pageY would be better.

**Comment by bennlich** [comment]
Do you have a local copy of agentscript you can build? Can you see if your fix works?

**Comment by bennlich** [comment]
On second thought, I don't think pageX/pageY is what we want. We want offsetX/offsetY relative to the agentscript div.

**Comment by bennlich** [comment]
I can't get any mouse events from patches in tiledroplets. I think it's because of the leaflet layer. Were you able to get mouse events without making any other modifications?

**Comment by m0ose** [comment]
Yeah. It seems to work. I have version at http://www.simtable.com/sketches/agentscript/models/tiledroplets.html. This is using a changed mouse.js file 'though. Its using pageX/pageY, which I agree is probably the wrong way to do it.

**Comment by bennlich** [comment]
Cool. I think it should be fixed now. Btw, here's the agentscript-y way to work with patches in a radius:

```javascript
var pats = this.patches.patchRect(patch, 7, 7);
pats.forEach(function(patch) {
    patch.sprout(1);
});
```

**Comment by m0ose** [comment]
Awesome. Nice work.

Cody Smith
