### ISSUE TITLE
demo sketches require options to work

### ISSUE THREAD

**Issue by konsumer** [backspaces/agentscript#89]
I am trying to quickly get something running in the browser and all the demos in the `sketches` folder produce this error:
```
Uncaught Error: Model constructor: use options object; see console for defaults.
```

**Comment by bennlich** [comment]
Hey, @konsumer . For now, check out the examples in `/models` instead. The files in `/sketches` use an old syntax that we just deprecated (3 hours ago, actually =P). I'll update the `/sketches` files right away though. Thanks for this.

**Comment by konsumer** [comment]
Oh, sweet. Thanks!

**Comment by bennlich** [comment]
Should be fixed with https://github.com/backspaces/agentscript/commit/7e2f8eaa6f2743934bf61cfec0ef69f53d0b9e33 now too.

**Comment by backspaces** [comment]
Hey, nice catch, thanks.
